### ISSUE TITLE
没找到齿轮

### ISSUE THREAD

**Issue by yanabcd** [newfyu/OpenCopilot#2]
如题，软件没有齿轮按钮

**Comment by newfyu** [comment]
窗口模式下，下面第4个按钮。无框模式下没有，替换为了拖动按钮。

**Comment by yanabcd** [comment]
![image](https://github.com/newfyu/OpenCopilot/assets/48935623/a46f1dd1-3c58-4136-b6b1-23e1ee87bcf4)
在哪？

**Comment by yanabcd** [comment]
![image](https://github.com/newfyu/OpenCopilot/assets/48935623/18c3dd0f-a124-42c8-a1fc-0f0318294b0e)
zai在哪？
