### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by hhrensheng** [newfyu/OpenCopilot#8]
![image](https://github.com/newfyu/Tianshu/assets/29398035/e1ff0a9f-560e-4875-896d-a02dea13b431)
一直报错，已经配置key和代理
![image](https://github.com/newfyu/Tianshu/assets/29398035/17161788-d74c-4fc0-840c-e2846952a4ce)

**Comment by hhrensheng** [comment]
![image](https://github.com/newfyu/Tianshu/assets/29398035/fc93a93a-c2b4-4dfe-8606-72f41b0421b4)
日志没有错误信息

**Comment by hhrensheng** [comment]
我通过win11 命令行打开提示
![image](https://github.com/newfyu/Tianshu/assets/29398035/9f6fd03d-861c-4b97-bdce-8f838662cfe6)

**Comment by newfyu** [comment]
> ![image](https://user-images.githubusercontent.com/29398035/273370014-fc93a93a-c2b4-4dfe-8606-72f41b0421b4.png) 日志没有错误信息

没看出来问题在哪儿，能成功发送并且一直在尝试，但没有返回，看起来是网络问题，代理地址我测试了也还有效，是否api-key失效了？

**Comment by hhrensheng** [comment]
![image](https://github.com/newfyu/Tianshu/assets/29398035/f836ea85-4459-4e6f-acb5-182ddbf78d0a)
这样是没有失效吧。会不会是我电脑本身有其他python环境给干扰了？

**Comment by newfyu** [comment]
6月份创建的，一般免费的就三个月，可能是失效了

发自我的 iPhone

在 2023年10月18日，08:50，hhrensheng ***@***.***> 写道：

﻿

[image]<https://user-images.githubusercontent.com/29398035/276042504-f836ea85-4459-4e6f-acb5-182ddbf78d0a.png>
这样是没有失效吧。会不会是我电脑本身有其他python环境给干扰了？

**Comment by hhrensheng** [comment]
![image](https://github.com/newfyu/Tianshu/assets/29398035/78124f43-603d-4d7c-b73d-150a2fbf00f1)
还是不行，
![image](https://github.com/newfyu/Tianshu/assets/29398035/148dab03-16db-4913-b1f2-731da4ad8b34)
已经更换了key，
![image](https://github.com/newfyu/Tianshu/assets/29398035/0c32eab0-e3a4-4a5c-8fea-5e698c4735eb)

**Comment by newfyu** [comment]
下载一下v0.6.2重新安装试试
启动后显示这个页面了吗
![image](https://github.com/newfyu/Tianshu/assets/43229758/ceb9dca3-4ec6-408d-91a0-da37b3953c83)

**Comment by hhrensheng** [comment]
用的就是最新的，是的，打开就是这个界面

**Comment by newfyu** [comment]
> 用的就是最新的，是的，打开就是这个界面

看起来是正常的，感觉还是key的问题，你可以查一下key的用量，点左边的usage。也可以给我个联系方式比如邮箱，给你私信一个key测试
![image](https://github.com/newfyu/Tianshu/assets/43229758/940cc682-d81c-4ee9-984e-4b7a8dc8d34e)

**Comment by hhrensheng** [comment]
![image](https://github.com/newfyu/Tianshu/assets/29398035/08f0cfa9-afcb-4d2e-98ea-ee6afeb5376b)
本月用量是0，最近的一次使用时8月
![image](https://github.com/newfyu/Tianshu/assets/29398035/57e03a5b-5d9e-45f9-8a20-00022b44ae2f)
我的邮箱是gh894563420@gmail.com

**Comment by newfyu** [comment]
红色表示已经过期了，邮件给你发了一个测试

**Comment by hhrensheng** [comment]
说的很对，是key的问题😮‍💨，请问一下现在想使用api就必须付费了吗

**Comment by newfyu** [comment]
新注册免费送3个月共5美元，不嫌麻烦就自己注册。后续正常使用只有付费。

> 2023年10月19日 13:28，hhrensheng ***@***.***> 写道：
> 
>

**Comment by hhrensheng** [comment]
了解 感谢
